--Summary of priviledges that had to be manually added on the IRMQQ schema
--=====================================================================
--To compile the code
GRANT SELECT ON  IPN_NW_TYPES TO CHL_CLARO_IRMQQ_REPORTS 
GRANT SELECT ON  IPN_IBR_CELL_REPORT_DATA TO CHL_CLARO_IRMQQ_REPORTS
GRANT DELETE ON  IPN_IBR_CELL_REPORT_DATA TO CHL_CLARO_IRMQQ_REPORTS
GRANT SELECT ON  DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS
GRANT DELETE ON  DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS
GRANT SELECT ON  IPN_PREFERRED_MODE_TYPES TO CHL_CLARO_IRMQQ_REPORTS

--=====================================================================
-- For runtime
GRANT SELECT ON  IPN_NW_TYPES TO CHL_CLARO_IRMQQ_REPORTS 
GRANT SELECT ON  IPN_IBR_CELL_REPORT_DATA TO CHL_CLARO_IRMQQ_REPORTS
GRANT DELETE ON  IPN_IBR_CELL_REPORT_DATA TO CHL_CLARO_IRMQQ_REPORTS
GRANT SELECT ON  DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS
GRANT DELETE ON  DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS
GRANT SELECT ON  IPN_PREFERRED_MODE_TYPES TO CHL_CLARO_IRMQQ_REPORTS

GRANT SELECT ON DB_INSTALLED_VERSIONS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GSM_COUNTRIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GSM_NETWORKS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GSM_IMSI_PREFIXES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON SGA_OUT_COMM TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON PRIVATE_COMM TO CHL_CLARO_IRMQQ_REPORTS;         
GRANT SELECT ON GA_ACCOUNTS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON OVMD_SERVICE_PROPERTY_VALUES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON IPN_SERVICE_PROPERTIES_VALUES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON OVMD_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GA_PRODUCT_TREE_CONF TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GA_PROPERTY_VALUES_CONF  TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON IPN_REJECTION_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IRM_OP_CODE_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PROV_PROPERTIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGNS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGN_CATEGORIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGN_CATEGORY_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_DEVICE_CONFIGURATION TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GA_W_COUNTERS_HISTORY TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_DISTRIBUTION_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_ROAMING_DISTRIBUTION TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_NETWORK_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS;


/*
====================================================================
REPORTS_PROVISIONING_PKG
====================================================================
GRANT SELECT ON  GSM_COUNTRIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GSM_NETWORKS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GSM_IMSI_PREFIXES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  SGA_OUT_COMM TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PRIVATE_COMM TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  DB_INSTALLED_VERSIONS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GA_ACCOUNTS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  OVMD_SERVICE_PROPERTY_VALUES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_SERVICE_PROPERTIES_VALUES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  OVMD_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GA_PRODUCT_TREE_CONF TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GA_PROPERTY_VALUES_CONF TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_REJECTION_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IRM_OP_CODE_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PROV_PROPERTIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGNS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGN_CATEGORIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  PSMS_CAMPAIGN_CATEGORY_TYPES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_DEVICE_CONFIGURATION TO CHL_CLARO_IRMQQ_REPORTS;
=======================================================================
PACKAGE REPORTS_PKG
====================================================================
GRANT SELECT ON  GA_W_COUNTERS_HISTORY TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GSM_NETWORKS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GSM_IMSI_PREFIXES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GSM_COUNTRIES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_DISTRIBUTION_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_ROAMING_DISTRIBUTION TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  IPN_NETWORK_PROFILES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON  GA_ACCOUNTS TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON OVMD_SERVICE_PROPERTY_VALUES TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON DEBUG_GEN_W_SDR TO CHL_CLARO_IRMQQ_REPORTS;
GRANT SELECT ON GA_PRODUCT_TREE_CONF TO CHL_CLARO_IRMQQ_REPORTS;
*/