column SEGMENT_NAME format A50
SELECT * FROM (
  SELECT 
    OWNER, SEGMENT_NAME, BYTES/1024/1024 SIZE_MB 
  FROM 
    DBA_SEGMENTS 
 WHERE
      SEGMENT_TYPE = 'TABLE'

  ORDER BY 
    BYTES/1024/1024  DESC ) WHERE ROWNUM <= 10;